name: RubiksUHC
version: 1.0-SNAPSHOT
main: me.qther.rubiksuhc.RubiksUHC
api-version: 1.13
load: STARTUP
authors: [Qther]
description: Made for Rubik's Craft SMP.
commands:
  ruhc:
    description: Opens a menu for RubiksUHC.
    usage: /ruhc
